version: 2.1
jobs:
    save_hello_world_output:
        defaults: &defaults
        docker:
            - image: circleci/node:13.8.0
        steps:
            - run: echo "practice saving data in jobs" > ~/output.txt
            - persist_to_workspace:
                  root: ~/
                  paths:
                      - output.txt

    print_output_file:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run: cat ~/output.txt
workflows:
    persist_data_workflow:
        jobs:
            - save_hello_world_output
            - print_output_file:
                  requires:
                      - save_hello_world_output
